
# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ../data/dataset_transformed/drone/train.txt
val: ../data/dataset_transformed/drone/validation.txt
test: ../data/dataset_transformed/drone/test.txt

mesh: ../data/dataset_transformed/drone/mesh/
tr_range: ../data/dataset_transformed/drone/training_range.txt
# backup : ../backup/benchvise
names : ["drone"]

# background_path: "../data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 0.2
gpus : 0

nc: 1  # number of classes

fx: 320
fy: 320
u0: 320
v0: 240

